<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" doctype-system="about:legacy-compat"/>

<xsl:template match="/">
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <meta name="robots" content="noindex,follow"/>
  <title>XML Sitemap &#8212; DigiVeritaz</title>
  <style>
    :root{--g:#22c55e;--g2:#16a34a;--ink:#0f172a;--mut:#64748b;--line:#e5e7eb;--bg:#f8fafc;}
    *{box-sizing:border-box}
    body{margin:0;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;color:var(--ink);background:var(--bg);line-height:1.55}
    .wrap{max-width:1120px;margin:0 auto;padding:34px 20px 70px}
    .brand{display:flex;align-items:center;gap:10px;font-weight:800;font-size:1.2rem;margin-bottom:26px}
    .brand img{height:30px;width:auto}
    .brand b{color:var(--g)}
    h1{font-size:1.95rem;margin:0 0 6px;letter-spacing:-.02em}
    .sub{color:var(--mut);margin:0 0 22px;font-size:.95rem;max-width:760px}
    .sub strong{color:var(--ink)}
    .count{display:inline-block;background:#ecfdf5;color:var(--g2);border:1px solid #bbf7d0;border-radius:999px;padding:3px 12px;font-size:.8rem;font-weight:600;margin-bottom:18px}
    table{width:100%;border-collapse:collapse;background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden;font-size:.9rem;box-shadow:0 1px 2px rgba(15,23,42,.04)}
    thead th{text-align:left;background:linear-gradient(90deg,var(--g),var(--g2));color:#fff;font-weight:600;padding:13px 16px;font-size:.74rem;letter-spacing:.05em;text-transform:uppercase}
    tbody td{padding:11px 16px;border-top:1px solid var(--line);vertical-align:top}
    tbody tr:nth-child(even){background:#f9fafb}
    tbody tr:hover{background:#f0fdf4}
    a{color:var(--g2);text-decoration:none;word-break:break-all}
    a:hover{text-decoration:underline}
    .num{color:var(--mut);white-space:nowrap;font-variant-numeric:tabular-nums}
    .idx{color:var(--mut);width:46px;text-align:right;white-space:nowrap}
    footer{margin-top:22px;color:var(--mut);font-size:.8rem}
    @media(max-width:640px){
      thead{display:none}
      tbody td{display:block;padding:3px 16px;border-top:none}
      tbody td.idx{display:none}
      tbody tr{display:block;border-top:1px solid var(--line);padding:10px 0}
      tbody td:first-child{padding-top:10px;font-weight:600}
    }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="brand"><img src="/assets/logo.webp?v=3" alt="DigiVeritaz"/><span><b>Digi</b>Veritaz</span></div>

    <xsl:choose>
      <!-- ============ SITEMAP INDEX ============ -->
      <xsl:when test="s:sitemapindex">
        <h1>XML Sitemap Index</h1>
        <p class="sub">This is an XML sitemap index for <strong>DigiVeritaz</strong>, generated for search engines such as Google and Bing. Each entry below is a separate sitemap.</p>
        <div class="count"><xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps</div>
        <table>
          <thead><tr><th class="idx">#</th><th>Sitemap</th><th>Last Modified</th></tr></thead>
          <tbody>
            <xsl:for-each select="s:sitemapindex/s:sitemap">
              <tr>
                <td class="idx"><xsl:value-of select="position()"/></td>
                <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                <td class="num"><xsl:value-of select="s:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </xsl:when>

      <!-- ============ URL SET ============ -->
      <xsl:when test="s:urlset">
        <h1>XML Sitemap</h1>
        <p class="sub">This is an XML sitemap for <strong>DigiVeritaz</strong>, generated for search engines such as Google and Bing. It lists the pages we want indexed.</p>
        <div class="count"><xsl:value-of select="count(s:urlset/s:url)"/> URLs</div>
        <table>
          <thead><tr><th class="idx">#</th><th>URL</th><th>Last Modified</th><th>Change Freq</th><th>Priority</th></tr></thead>
          <tbody>
            <xsl:for-each select="s:urlset/s:url">
              <tr>
                <td class="idx"><xsl:value-of select="position()"/></td>
                <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                <td class="num"><xsl:value-of select="s:lastmod"/></td>
                <td class="num"><xsl:value-of select="s:changefreq"/></td>
                <td class="num"><xsl:value-of select="s:priority"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </xsl:when>
    </xsl:choose>

    <footer>Generated by DigiVeritaz &#8226; <a href="https://www.digiveritaz.com/">digiveritaz.com</a> &#8226; This page is a human-friendly view; search engines read the raw XML.</footer>
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
